// File generated by FlutterFire CLI.
// Dummy configuration. You MUST run `flutterfire configure` to generate the real file.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXGG-lzO4pGErgRkS2XdIdEYC8c58Zsjs',
    appId: '1:859886456767:web:92896765f84b6ffcac9b0a',
    messagingSenderId: '859886456767',
    projectId: 'nasuba-voyage',
    authDomain: 'nasuba-voyage.firebaseapp.com',
    databaseURL: 'https://nasuba-voyage-default-rtdb.firebaseio.com',
    storageBucket: 'nasuba-voyage.firebasestorage.app',
    measurementId: 'G-1EGXCTFKBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoR4uYE7w19INleIferflwvISNxJcjsvY',
    appId: '1:859886456767:android:59a31d760adeabdcac9b0a',
    messagingSenderId: '859886456767',
    projectId: 'nasuba-voyage',
    databaseURL: 'https://nasuba-voyage-default-rtdb.firebaseio.com',
    storageBucket: 'nasuba-voyage.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0gTPvBA3TMcV3dJZmSLS-KRQKcFm_SyQ',
    appId: '1:859886456767:ios:1f03e90a4cf9ea18ac9b0a',
    messagingSenderId: '859886456767',
    projectId: 'nasuba-voyage',
    databaseURL: 'https://nasuba-voyage-default-rtdb.firebaseio.com',
    storageBucket: 'nasuba-voyage.firebasestorage.app',
    iosBundleId: 'com.example.nasubaDriverApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_ME_API_KEY',
    appId: '1:1234567890:ios:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'nasuba-voyage',
    storageBucket: 'nasuba-voyage.appspot.com',
    iosBundleId: 'com.nasuba.voyage.driver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'REPLACE_ME_API_KEY',
    appId: '1:1234567890:web:abcdef',
    messagingSenderId: '1234567890',
    projectId: 'nasuba-voyage',
    authDomain: 'nasuba-voyage.firebaseapp.com',
    storageBucket: 'nasuba-voyage.appspot.com',
  );
}
